// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package store

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :execrows
DELETE FROM idempotency_keys WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT organization_id, idempotency_key, request_hash, response_code, response_body, created_at, expires_at FROM idempotency_keys
WHERE organization_id = $1 AND idempotency_key = $2 AND expires_at > now()
`

type GetIdempotencyKeyParams struct {
	OrganizationID uuid.UUID
	IdempotencyKey string
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.OrganizationID, arg.IdempotencyKey)
	var i IdempotencyKey
	err := row.Scan(
		&i.OrganizationID,
		&i.IdempotencyKey,
		&i.RequestHash,
		&i.ResponseCode,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :one

INSERT INTO audit_logs (organization_id, actor_user_id, actor_api_key_id, action, entity_type, entity_id, ip_address, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type InsertAuditLogParams struct {
	OrganizationID uuid.NullUUID
	ActorUserID    uuid.NullUUID
	ActorApiKeyID  uuid.NullUUID
	Action         string
	EntityType     *string
	EntityID       *string
	IpAddress      *netip.Addr
	Metadata       []byte
}

// Audit trail and API idempotency. Owned by internal/audit.
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.OrganizationID,
		arg.ActorUserID,
		arg.ActorApiKeyID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.IpAddress,
		arg.Metadata,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :execrows
INSERT INTO idempotency_keys (organization_id, idempotency_key, request_hash)
VALUES ($1, $2, $3)
ON CONFLICT (organization_id, idempotency_key) DO NOTHING
`

type InsertIdempotencyKeyParams struct {
	OrganizationID uuid.UUID
	IdempotencyKey string
	RequestHash    []byte
}

func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertIdempotencyKey, arg.OrganizationID, arg.IdempotencyKey, arg.RequestHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, organization_id, actor_user_id, actor_api_key_id, action, entity_type, entity_id, ip_address, metadata, created_at FROM audit_logs
WHERE organization_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogsParams struct {
	OrganizationID uuid.NullUUID
	Limit          int32
	Offset         int32
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ActorUserID,
			&i.ActorApiKeyID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.IpAddress,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsForEntity = `-- name: ListAuditLogsForEntity :many
SELECT id, organization_id, actor_user_id, actor_api_key_id, action, entity_type, entity_id, ip_address, metadata, created_at FROM audit_logs
WHERE entity_type = $1 AND entity_id = $2
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListAuditLogsForEntityParams struct {
	EntityType *string
	EntityID   *string
	Limit      int32
}

func (q *Queries) ListAuditLogsForEntity(ctx context.Context, arg ListAuditLogsForEntityParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsForEntity, arg.EntityType, arg.EntityID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ActorUserID,
			&i.ActorApiKeyID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.IpAddress,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const storeIdempotentResponse = `-- name: StoreIdempotentResponse :exec
UPDATE idempotency_keys
SET response_code = $3, response_body = $4
WHERE organization_id = $1 AND idempotency_key = $2
`

type StoreIdempotentResponseParams struct {
	OrganizationID uuid.UUID
	IdempotencyKey string
	ResponseCode   pgtype.Int2
	ResponseBody   []byte
}

func (q *Queries) StoreIdempotentResponse(ctx context.Context, arg StoreIdempotentResponseParams) error {
	_, err := q.db.Exec(ctx, storeIdempotentResponse,
		arg.OrganizationID,
		arg.IdempotencyKey,
		arg.ResponseCode,
		arg.ResponseBody,
	)
	return err
}
