// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chain.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countOrganizationAddresses = `-- name: CountOrganizationAddresses :one
SELECT count(*) FROM addresses WHERE organization_id = $1
`

func (q *Queries) CountOrganizationAddresses(ctx context.Context, organizationID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizationAddresses, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrganizationTransfers = `-- name: CountOrganizationTransfers :one
SELECT count(*)
FROM transfers t
JOIN addresses ad ON ad.id = t.address_id
WHERE ad.organization_id = $1
`

func (q *Queries) CountOrganizationTransfers(ctx context.Context, organizationID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizationTransfers, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAddress = `-- name: CreateAddress :one

INSERT INTO addresses (network_id, provider_id, wallet_id, organization_id, address, memo, kind, derivation_index, external_address_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, network_id, provider_id, wallet_id, organization_id, address, memo, kind, derivation_index, external_address_id, is_active, last_used_at, created_at
`

type CreateAddressParams struct {
	NetworkID         int16
	ProviderID        int16
	WalletID          uuid.UUID
	OrganizationID    uuid.NullUUID
	Address           string
	Memo              *string
	Kind              WalletKind
	DerivationIndex   pgtype.Int8
	ExternalAddressID *string
}

// Addresses -------------------------------------------------------------------
func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, createAddress,
		arg.NetworkID,
		arg.ProviderID,
		arg.WalletID,
		arg.OrganizationID,
		arg.Address,
		arg.Memo,
		arg.Kind,
		arg.DerivationIndex,
		arg.ExternalAddressID,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.NetworkID,
		&i.ProviderID,
		&i.WalletID,
		&i.OrganizationID,
		&i.Address,
		&i.Memo,
		&i.Kind,
		&i.DerivationIndex,
		&i.ExternalAddressID,
		&i.IsActive,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createTransfer = `-- name: CreateTransfer :one

INSERT INTO transfers (transaction_id, network_id, asset_id, log_index, from_address, to_address, to_memo, amount, direction, address_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (transaction_id, log_index) DO NOTHING
RETURNING id, transaction_id, network_id, asset_id, log_index, from_address, to_address, to_memo, amount, direction, address_id, created_at
`

type CreateTransferParams struct {
	TransactionID uuid.UUID
	NetworkID     int16
	AssetID       int16
	LogIndex      int32
	FromAddress   *string
	ToAddress     string
	ToMemo        *string
	Amount        pgtype.Numeric
	Direction     TransferDirection
	AddressID     uuid.NullUUID
}

// Transfers -------------------------------------------------------------------
func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error) {
	row := q.db.QueryRow(ctx, createTransfer,
		arg.TransactionID,
		arg.NetworkID,
		arg.AssetID,
		arg.LogIndex,
		arg.FromAddress,
		arg.ToAddress,
		arg.ToMemo,
		arg.Amount,
		arg.Direction,
		arg.AddressID,
	)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.NetworkID,
		&i.AssetID,
		&i.LogIndex,
		&i.FromAddress,
		&i.ToAddress,
		&i.ToMemo,
		&i.Amount,
		&i.Direction,
		&i.AddressID,
		&i.CreatedAt,
	)
	return i, err
}

const createWallet = `-- name: CreateWallet :one


INSERT INTO wallets (provider_id, network_id, kind, name, key_ref, xpub, derivation_path, external_wallet_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, provider_id, network_id, kind, name, key_ref, xpub, derivation_path, next_index, external_wallet_id, is_active, created_at, updated_at
`

type CreateWalletParams struct {
	ProviderID       int16
	NetworkID        int16
	Kind             WalletKind
	Name             string
	KeyRef           *string
	Xpub             *string
	DerivationPath   *string
	ExternalWalletID *string
}

// Chain: wallets, addresses, observed transactions and transfers, scanner
// cursors. Owned by internal/chain. Knows nothing about invoices or merchants
// beyond the organization_id stamped on deposit addresses.
// Wallets ---------------------------------------------------------------------
func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, createWallet,
		arg.ProviderID,
		arg.NetworkID,
		arg.Kind,
		arg.Name,
		arg.KeyRef,
		arg.Xpub,
		arg.DerivationPath,
		arg.ExternalWalletID,
	)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.NetworkID,
		&i.Kind,
		&i.Name,
		&i.KeyRef,
		&i.Xpub,
		&i.DerivationPath,
		&i.NextIndex,
		&i.ExternalWalletID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findAddress = `-- name: FindAddress :one
SELECT id, network_id, provider_id, wallet_id, organization_id, address, memo, kind, derivation_index, external_address_id, is_active, last_used_at, created_at FROM addresses
WHERE network_id = $1 AND address = $2 AND memo IS NOT DISTINCT FROM $3
`

type FindAddressParams struct {
	NetworkID int16
	Address   string
	Memo      *string
}

func (q *Queries) FindAddress(ctx context.Context, arg FindAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, findAddress, arg.NetworkID, arg.Address, arg.Memo)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.NetworkID,
		&i.ProviderID,
		&i.WalletID,
		&i.OrganizationID,
		&i.Address,
		&i.Memo,
		&i.Kind,
		&i.DerivationIndex,
		&i.ExternalAddressID,
		&i.IsActive,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveWallet = `-- name: GetActiveWallet :one
SELECT id, provider_id, network_id, kind, name, key_ref, xpub, derivation_path, next_index, external_wallet_id, is_active, created_at, updated_at FROM wallets
WHERE network_id = $1 AND kind = $2 AND is_active
  AND (provider_id = $3 OR $3 IS NULL)
ORDER BY created_at
LIMIT 1
`

type GetActiveWalletParams struct {
	NetworkID  int16
	Kind       WalletKind
	ProviderID pgtype.Int2
}

func (q *Queries) GetActiveWallet(ctx context.Context, arg GetActiveWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, getActiveWallet, arg.NetworkID, arg.Kind, arg.ProviderID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.NetworkID,
		&i.Kind,
		&i.Name,
		&i.KeyRef,
		&i.Xpub,
		&i.DerivationPath,
		&i.NextIndex,
		&i.ExternalWalletID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAddress = `-- name: GetAddress :one
SELECT id, network_id, provider_id, wallet_id, organization_id, address, memo, kind, derivation_index, external_address_id, is_active, last_used_at, created_at FROM addresses WHERE id = $1
`

func (q *Queries) GetAddress(ctx context.Context, id uuid.UUID) (Address, error) {
	row := q.db.QueryRow(ctx, getAddress, id)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.NetworkID,
		&i.ProviderID,
		&i.WalletID,
		&i.OrganizationID,
		&i.Address,
		&i.Memo,
		&i.Kind,
		&i.DerivationIndex,
		&i.ExternalAddressID,
		&i.IsActive,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getChainCursor = `-- name: GetChainCursor :one

SELECT provider_id, network_id, last_scanned_block, last_scanned_hash, external_cursor, updated_at FROM chain_cursors WHERE provider_id = $1 AND network_id = $2
`

type GetChainCursorParams struct {
	ProviderID int16
	NetworkID  int16
}

// Cursors ---------------------------------------------------------------------
func (q *Queries) GetChainCursor(ctx context.Context, arg GetChainCursorParams) (ChainCursor, error) {
	row := q.db.QueryRow(ctx, getChainCursor, arg.ProviderID, arg.NetworkID)
	var i ChainCursor
	err := row.Scan(
		&i.ProviderID,
		&i.NetworkID,
		&i.LastScannedBlock,
		&i.LastScannedHash,
		&i.ExternalCursor,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, network_id, provider_id, hash, block_number, block_hash, block_timestamp, from_address, to_address, status, confirmations, fee_native, fee_details, external_tx_id, raw, first_seen_at, confirmed_at FROM transactions WHERE id = $1
`

func (q *Queries) GetTransaction(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.NetworkID,
		&i.ProviderID,
		&i.Hash,
		&i.BlockNumber,
		&i.BlockHash,
		&i.BlockTimestamp,
		&i.FromAddress,
		&i.ToAddress,
		&i.Status,
		&i.Confirmations,
		&i.FeeNative,
		&i.FeeDetails,
		&i.ExternalTxID,
		&i.Raw,
		&i.FirstSeenAt,
		&i.ConfirmedAt,
	)
	return i, err
}

const getTransactionByHash = `-- name: GetTransactionByHash :one
SELECT id, network_id, provider_id, hash, block_number, block_hash, block_timestamp, from_address, to_address, status, confirmations, fee_native, fee_details, external_tx_id, raw, first_seen_at, confirmed_at FROM transactions WHERE network_id = $1 AND hash = $2
`

type GetTransactionByHashParams struct {
	NetworkID int16
	Hash      string
}

func (q *Queries) GetTransactionByHash(ctx context.Context, arg GetTransactionByHashParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByHash, arg.NetworkID, arg.Hash)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.NetworkID,
		&i.ProviderID,
		&i.Hash,
		&i.BlockNumber,
		&i.BlockHash,
		&i.BlockTimestamp,
		&i.FromAddress,
		&i.ToAddress,
		&i.Status,
		&i.Confirmations,
		&i.FeeNative,
		&i.FeeDetails,
		&i.ExternalTxID,
		&i.Raw,
		&i.FirstSeenAt,
		&i.ConfirmedAt,
	)
	return i, err
}

const getTransfer = `-- name: GetTransfer :one
SELECT id, transaction_id, network_id, asset_id, log_index, from_address, to_address, to_memo, amount, direction, address_id, created_at FROM transfers WHERE id = $1
`

func (q *Queries) GetTransfer(ctx context.Context, id uuid.UUID) (Transfer, error) {
	row := q.db.QueryRow(ctx, getTransfer, id)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.NetworkID,
		&i.AssetID,
		&i.LogIndex,
		&i.FromAddress,
		&i.ToAddress,
		&i.ToMemo,
		&i.Amount,
		&i.Direction,
		&i.AddressID,
		&i.CreatedAt,
	)
	return i, err
}

const getTransferByTxLog = `-- name: GetTransferByTxLog :one
SELECT id, transaction_id, network_id, asset_id, log_index, from_address, to_address, to_memo, amount, direction, address_id, created_at FROM transfers WHERE transaction_id = $1 AND log_index = $2
`

type GetTransferByTxLogParams struct {
	TransactionID uuid.UUID
	LogIndex      int32
}

func (q *Queries) GetTransferByTxLog(ctx context.Context, arg GetTransferByTxLogParams) (Transfer, error) {
	row := q.db.QueryRow(ctx, getTransferByTxLog, arg.TransactionID, arg.LogIndex)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.NetworkID,
		&i.AssetID,
		&i.LogIndex,
		&i.FromAddress,
		&i.ToAddress,
		&i.ToMemo,
		&i.Amount,
		&i.Direction,
		&i.AddressID,
		&i.CreatedAt,
	)
	return i, err
}

const getWallet = `-- name: GetWallet :one
SELECT id, provider_id, network_id, kind, name, key_ref, xpub, derivation_path, next_index, external_wallet_id, is_active, created_at, updated_at FROM wallets WHERE id = $1
`

func (q *Queries) GetWallet(ctx context.Context, id uuid.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWallet, id)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.NetworkID,
		&i.Kind,
		&i.Name,
		&i.KeyRef,
		&i.Xpub,
		&i.DerivationPath,
		&i.NextIndex,
		&i.ExternalWalletID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAddressBalances = `-- name: ListAddressBalances :many
SELECT b.address_id, b.asset_id, b.balance, b.as_of_block, b.updated_at, a.code AS asset_code, a.symbol
FROM address_balances b
JOIN assets a ON a.id = b.asset_id
WHERE b.address_id = $1
ORDER BY a.code
`

type ListAddressBalancesRow struct {
	AddressBalance AddressBalance
	AssetCode      string
	Symbol         string
}

func (q *Queries) ListAddressBalances(ctx context.Context, addressID uuid.UUID) ([]ListAddressBalancesRow, error) {
	rows, err := q.db.Query(ctx, listAddressBalances, addressID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAddressBalancesRow{}
	for rows.Next() {
		var i ListAddressBalancesRow
		if err := rows.Scan(
			&i.AddressBalance.AddressID,
			&i.AddressBalance.AssetID,
			&i.AddressBalance.Balance,
			&i.AddressBalance.AsOfBlock,
			&i.AddressBalance.UpdatedAt,
			&i.AssetCode,
			&i.Symbol,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationAddresses = `-- name: ListOrganizationAddresses :many
SELECT a.id, a.network_id, a.provider_id, a.wallet_id, a.organization_id, a.address, a.memo, a.kind, a.derivation_index, a.external_address_id, a.is_active, a.last_used_at, a.created_at, n.code AS network_code
FROM addresses a
JOIN networks n ON n.id = a.network_id
WHERE a.organization_id = $1
ORDER BY a.created_at DESC
LIMIT $2 OFFSET $3
`

type ListOrganizationAddressesParams struct {
	OrganizationID uuid.NullUUID
	Limit          int32
	Offset         int32
}

type ListOrganizationAddressesRow struct {
	Address     Address
	NetworkCode string
}

func (q *Queries) ListOrganizationAddresses(ctx context.Context, arg ListOrganizationAddressesParams) ([]ListOrganizationAddressesRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationAddresses, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationAddressesRow{}
	for rows.Next() {
		var i ListOrganizationAddressesRow
		if err := rows.Scan(
			&i.Address.ID,
			&i.Address.NetworkID,
			&i.Address.ProviderID,
			&i.Address.WalletID,
			&i.Address.OrganizationID,
			&i.Address.Address,
			&i.Address.Memo,
			&i.Address.Kind,
			&i.Address.DerivationIndex,
			&i.Address.ExternalAddressID,
			&i.Address.IsActive,
			&i.Address.LastUsedAt,
			&i.Address.CreatedAt,
			&i.NetworkCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationTransfers = `-- name: ListOrganizationTransfers :many
SELECT t.id, t.transaction_id, t.network_id, t.asset_id, t.log_index, t.from_address, t.to_address, t.to_memo, t.amount, t.direction, t.address_id, t.created_at, tx.id, tx.network_id, tx.provider_id, tx.hash, tx.block_number, tx.block_hash, tx.block_timestamp, tx.from_address, tx.to_address, tx.status, tx.confirmations, tx.fee_native, tx.fee_details, tx.external_tx_id, tx.raw, tx.first_seen_at, tx.confirmed_at, a.code AS asset_code, a.symbol, a.decimals, n.code AS network_code, n.name AS network_name, n.required_confirmations
FROM transfers t
JOIN addresses ad    ON ad.id = t.address_id
JOIN transactions tx ON tx.id = t.transaction_id
JOIN assets a        ON a.id = t.asset_id
JOIN networks n      ON n.id = t.network_id
WHERE ad.organization_id = $1
ORDER BY t.created_at DESC
LIMIT $2 OFFSET $3
`

type ListOrganizationTransfersParams struct {
	OrganizationID uuid.NullUUID
	Limit          int32
	Offset         int32
}

type ListOrganizationTransfersRow struct {
	Transfer              Transfer
	Transaction           Transaction
	AssetCode             string
	Symbol                string
	Decimals              int16
	NetworkCode           string
	NetworkName           string
	RequiredConfirmations int32
}

// Merchant activity: every transfer touching one of the merchant's addresses.
func (q *Queries) ListOrganizationTransfers(ctx context.Context, arg ListOrganizationTransfersParams) ([]ListOrganizationTransfersRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationTransfers, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationTransfersRow{}
	for rows.Next() {
		var i ListOrganizationTransfersRow
		if err := rows.Scan(
			&i.Transfer.ID,
			&i.Transfer.TransactionID,
			&i.Transfer.NetworkID,
			&i.Transfer.AssetID,
			&i.Transfer.LogIndex,
			&i.Transfer.FromAddress,
			&i.Transfer.ToAddress,
			&i.Transfer.ToMemo,
			&i.Transfer.Amount,
			&i.Transfer.Direction,
			&i.Transfer.AddressID,
			&i.Transfer.CreatedAt,
			&i.Transaction.ID,
			&i.Transaction.NetworkID,
			&i.Transaction.ProviderID,
			&i.Transaction.Hash,
			&i.Transaction.BlockNumber,
			&i.Transaction.BlockHash,
			&i.Transaction.BlockTimestamp,
			&i.Transaction.FromAddress,
			&i.Transaction.ToAddress,
			&i.Transaction.Status,
			&i.Transaction.Confirmations,
			&i.Transaction.FeeNative,
			&i.Transaction.FeeDetails,
			&i.Transaction.ExternalTxID,
			&i.Transaction.Raw,
			&i.Transaction.FirstSeenAt,
			&i.Transaction.ConfirmedAt,
			&i.AssetCode,
			&i.Symbol,
			&i.Decimals,
			&i.NetworkCode,
			&i.NetworkName,
			&i.RequiredConfirmations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingTransactions = `-- name: ListPendingTransactions :many
SELECT id, network_id, provider_id, hash, block_number, block_hash, block_timestamp, from_address, to_address, status, confirmations, fee_native, fee_details, external_tx_id, raw, first_seen_at, confirmed_at FROM transactions
WHERE network_id = $1 AND status = 'pending'
ORDER BY first_seen_at
LIMIT $2
`

type ListPendingTransactionsParams struct {
	NetworkID int16
	Limit     int32
}

func (q *Queries) ListPendingTransactions(ctx context.Context, arg ListPendingTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listPendingTransactions, arg.NetworkID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.NetworkID,
			&i.ProviderID,
			&i.Hash,
			&i.BlockNumber,
			&i.BlockHash,
			&i.BlockTimestamp,
			&i.FromAddress,
			&i.ToAddress,
			&i.Status,
			&i.Confirmations,
			&i.FeeNative,
			&i.FeeDetails,
			&i.ExternalTxID,
			&i.Raw,
			&i.FirstSeenAt,
			&i.ConfirmedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformAddresses = `-- name: ListPlatformAddresses :many
SELECT a.id, a.network_id, a.provider_id, a.wallet_id, a.organization_id, a.address, a.memo, a.kind, a.derivation_index, a.external_address_id, a.is_active, a.last_used_at, a.created_at, n.code AS network_code
FROM addresses a
JOIN networks n ON n.id = a.network_id
WHERE a.kind IN ('hot', 'cold', 'fee') AND a.is_active
ORDER BY n.code, a.kind, a.created_at DESC, a.id DESC
`

type ListPlatformAddressesRow struct {
	Address     Address
	NetworkCode string
}

// Newest first within (network, kind): several hot addresses can exist on one
// network, and routing must pick the same one every time.
func (q *Queries) ListPlatformAddresses(ctx context.Context) ([]ListPlatformAddressesRow, error) {
	rows, err := q.db.Query(ctx, listPlatformAddresses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlatformAddressesRow{}
	for rows.Next() {
		var i ListPlatformAddressesRow
		if err := rows.Scan(
			&i.Address.ID,
			&i.Address.NetworkID,
			&i.Address.ProviderID,
			&i.Address.WalletID,
			&i.Address.OrganizationID,
			&i.Address.Address,
			&i.Address.Memo,
			&i.Address.Kind,
			&i.Address.DerivationIndex,
			&i.Address.ExternalAddressID,
			&i.Address.IsActive,
			&i.Address.LastUsedAt,
			&i.Address.CreatedAt,
			&i.NetworkCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransfersForAddress = `-- name: ListTransfersForAddress :many
SELECT t.id, t.transaction_id, t.network_id, t.asset_id, t.log_index, t.from_address, t.to_address, t.to_memo, t.amount, t.direction, t.address_id, t.created_at, tx.id, tx.network_id, tx.provider_id, tx.hash, tx.block_number, tx.block_hash, tx.block_timestamp, tx.from_address, tx.to_address, tx.status, tx.confirmations, tx.fee_native, tx.fee_details, tx.external_tx_id, tx.raw, tx.first_seen_at, tx.confirmed_at
FROM transfers t
JOIN transactions tx ON tx.id = t.transaction_id
WHERE t.address_id = $1
ORDER BY t.created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransfersForAddressParams struct {
	AddressID uuid.NullUUID
	Limit     int32
	Offset    int32
}

type ListTransfersForAddressRow struct {
	Transfer    Transfer
	Transaction Transaction
}

func (q *Queries) ListTransfersForAddress(ctx context.Context, arg ListTransfersForAddressParams) ([]ListTransfersForAddressRow, error) {
	rows, err := q.db.Query(ctx, listTransfersForAddress, arg.AddressID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransfersForAddressRow{}
	for rows.Next() {
		var i ListTransfersForAddressRow
		if err := rows.Scan(
			&i.Transfer.ID,
			&i.Transfer.TransactionID,
			&i.Transfer.NetworkID,
			&i.Transfer.AssetID,
			&i.Transfer.LogIndex,
			&i.Transfer.FromAddress,
			&i.Transfer.ToAddress,
			&i.Transfer.ToMemo,
			&i.Transfer.Amount,
			&i.Transfer.Direction,
			&i.Transfer.AddressID,
			&i.Transfer.CreatedAt,
			&i.Transaction.ID,
			&i.Transaction.NetworkID,
			&i.Transaction.ProviderID,
			&i.Transaction.Hash,
			&i.Transaction.BlockNumber,
			&i.Transaction.BlockHash,
			&i.Transaction.BlockTimestamp,
			&i.Transaction.FromAddress,
			&i.Transaction.ToAddress,
			&i.Transaction.Status,
			&i.Transaction.Confirmations,
			&i.Transaction.FeeNative,
			&i.Transaction.FeeDetails,
			&i.Transaction.ExternalTxID,
			&i.Transaction.Raw,
			&i.Transaction.FirstSeenAt,
			&i.Transaction.ConfirmedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransfersForTransaction = `-- name: ListTransfersForTransaction :many
SELECT id, transaction_id, network_id, asset_id, log_index, from_address, to_address, to_memo, amount, direction, address_id, created_at FROM transfers WHERE transaction_id = $1 ORDER BY log_index
`

func (q *Queries) ListTransfersForTransaction(ctx context.Context, transactionID uuid.UUID) ([]Transfer, error) {
	rows, err := q.db.Query(ctx, listTransfersForTransaction, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transfer{}
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.NetworkID,
			&i.AssetID,
			&i.LogIndex,
			&i.FromAddress,
			&i.ToAddress,
			&i.ToMemo,
			&i.Amount,
			&i.Direction,
			&i.AddressID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWallets = `-- name: ListWallets :many
SELECT w.id, w.provider_id, w.network_id, w.kind, w.name, w.key_ref, w.xpub, w.derivation_path, w.next_index, w.external_wallet_id, w.is_active, w.created_at, w.updated_at, n.code AS network_code, p.code AS provider_code
FROM wallets w
JOIN networks n          ON n.id = w.network_id
JOIN payment_providers p ON p.id = w.provider_id
ORDER BY n.code, w.kind, w.name
`

type ListWalletsRow struct {
	Wallet       Wallet
	NetworkCode  string
	ProviderCode string
}

func (q *Queries) ListWallets(ctx context.Context) ([]ListWalletsRow, error) {
	rows, err := q.db.Query(ctx, listWallets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWalletsRow{}
	for rows.Next() {
		var i ListWalletsRow
		if err := rows.Scan(
			&i.Wallet.ID,
			&i.Wallet.ProviderID,
			&i.Wallet.NetworkID,
			&i.Wallet.Kind,
			&i.Wallet.Name,
			&i.Wallet.KeyRef,
			&i.Wallet.Xpub,
			&i.Wallet.DerivationPath,
			&i.Wallet.NextIndex,
			&i.Wallet.ExternalWalletID,
			&i.Wallet.IsActive,
			&i.Wallet.CreatedAt,
			&i.Wallet.UpdatedAt,
			&i.NetworkCode,
			&i.ProviderCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWatchedAddresses = `-- name: ListWatchedAddresses :many
SELECT address, memo FROM addresses
WHERE network_id = $1 AND is_active
`

type ListWatchedAddressesRow struct {
	Address string
	Memo    *string
}

func (q *Queries) ListWatchedAddresses(ctx context.Context, networkID int16) ([]ListWatchedAddressesRow, error) {
	rows, err := q.db.Query(ctx, listWatchedAddresses, networkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWatchedAddressesRow{}
	for rows.Next() {
		var i ListWatchedAddressesRow
		if err := rows.Scan(&i.Address, &i.Memo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reserveWalletIndex = `-- name: ReserveWalletIndex :one
UPDATE wallets SET next_index = next_index + 1
WHERE id = $1
RETURNING (next_index - 1)::bigint AS derivation_index
`

func (q *Queries) ReserveWalletIndex(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, reserveWalletIndex, id)
	var derivation_index int64
	err := row.Scan(&derivation_index)
	return derivation_index, err
}

const setAddressActive = `-- name: SetAddressActive :exec
UPDATE addresses SET is_active = $2 WHERE id = $1
`

type SetAddressActiveParams struct {
	ID       uuid.UUID
	IsActive bool
}

func (q *Queries) SetAddressActive(ctx context.Context, arg SetAddressActiveParams) error {
	_, err := q.db.Exec(ctx, setAddressActive, arg.ID, arg.IsActive)
	return err
}

const setWalletActive = `-- name: SetWalletActive :exec
UPDATE wallets SET is_active = $2 WHERE id = $1
`

type SetWalletActiveParams struct {
	ID       uuid.UUID
	IsActive bool
}

func (q *Queries) SetWalletActive(ctx context.Context, arg SetWalletActiveParams) error {
	_, err := q.db.Exec(ctx, setWalletActive, arg.ID, arg.IsActive)
	return err
}

const touchAddress = `-- name: TouchAddress :exec
UPDATE addresses SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAddress(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAddress, id)
	return err
}

const updateTransactionConfirmations = `-- name: UpdateTransactionConfirmations :one
UPDATE transactions
SET confirmations = $2,
    block_number  = COALESCE($3, block_number),
    status        = $4,
    confirmed_at  = CASE WHEN $4 = 'confirmed'::tx_status THEN COALESCE(confirmed_at, now()) ELSE confirmed_at END
WHERE id = $1
RETURNING id, network_id, provider_id, hash, block_number, block_hash, block_timestamp, from_address, to_address, status, confirmations, fee_native, fee_details, external_tx_id, raw, first_seen_at, confirmed_at
`

type UpdateTransactionConfirmationsParams struct {
	ID            uuid.UUID
	Confirmations int32
	BlockNumber   pgtype.Int8
	Status        TxStatus
}

func (q *Queries) UpdateTransactionConfirmations(ctx context.Context, arg UpdateTransactionConfirmationsParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransactionConfirmations,
		arg.ID,
		arg.Confirmations,
		arg.BlockNumber,
		arg.Status,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.NetworkID,
		&i.ProviderID,
		&i.Hash,
		&i.BlockNumber,
		&i.BlockHash,
		&i.BlockTimestamp,
		&i.FromAddress,
		&i.ToAddress,
		&i.Status,
		&i.Confirmations,
		&i.FeeNative,
		&i.FeeDetails,
		&i.ExternalTxID,
		&i.Raw,
		&i.FirstSeenAt,
		&i.ConfirmedAt,
	)
	return i, err
}

const upsertAddressBalance = `-- name: UpsertAddressBalance :exec
INSERT INTO address_balances (address_id, asset_id, balance, as_of_block)
VALUES ($1, $2, $3, $4)
ON CONFLICT (address_id, asset_id) DO UPDATE
    SET balance = EXCLUDED.balance, as_of_block = EXCLUDED.as_of_block, updated_at = now()
WHERE address_balances.as_of_block <= EXCLUDED.as_of_block
`

type UpsertAddressBalanceParams struct {
	AddressID uuid.UUID
	AssetID   int16
	Balance   pgtype.Numeric
	AsOfBlock int64
}

func (q *Queries) UpsertAddressBalance(ctx context.Context, arg UpsertAddressBalanceParams) error {
	_, err := q.db.Exec(ctx, upsertAddressBalance,
		arg.AddressID,
		arg.AssetID,
		arg.Balance,
		arg.AsOfBlock,
	)
	return err
}

const upsertChainCursor = `-- name: UpsertChainCursor :exec
INSERT INTO chain_cursors (provider_id, network_id, last_scanned_block, last_scanned_hash, external_cursor)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (provider_id, network_id) DO UPDATE
    SET last_scanned_block = EXCLUDED.last_scanned_block,
        last_scanned_hash  = EXCLUDED.last_scanned_hash,
        external_cursor    = EXCLUDED.external_cursor,
        updated_at         = now()
`

type UpsertChainCursorParams struct {
	ProviderID       int16
	NetworkID        int16
	LastScannedBlock int64
	LastScannedHash  *string
	ExternalCursor   *string
}

func (q *Queries) UpsertChainCursor(ctx context.Context, arg UpsertChainCursorParams) error {
	_, err := q.db.Exec(ctx, upsertChainCursor,
		arg.ProviderID,
		arg.NetworkID,
		arg.LastScannedBlock,
		arg.LastScannedHash,
		arg.ExternalCursor,
	)
	return err
}

const upsertTransaction = `-- name: UpsertTransaction :one

INSERT INTO transactions (network_id, provider_id, hash, block_number, block_hash, block_timestamp, from_address, to_address, status, confirmations, fee_native, fee_details, external_tx_id, raw)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
ON CONFLICT (network_id, hash) DO UPDATE
    SET block_number    = COALESCE(EXCLUDED.block_number, transactions.block_number),
        block_hash      = COALESCE(EXCLUDED.block_hash, transactions.block_hash),
        block_timestamp = COALESCE(EXCLUDED.block_timestamp, transactions.block_timestamp),
        status          = EXCLUDED.status,
        confirmations   = GREATEST(EXCLUDED.confirmations, transactions.confirmations),
        fee_native      = COALESCE(EXCLUDED.fee_native, transactions.fee_native),
        fee_details     = COALESCE(EXCLUDED.fee_details, transactions.fee_details),
        external_tx_id  = COALESCE(EXCLUDED.external_tx_id, transactions.external_tx_id),
        raw             = COALESCE(EXCLUDED.raw, transactions.raw),
        confirmed_at    = CASE WHEN EXCLUDED.status = 'confirmed' THEN COALESCE(transactions.confirmed_at, now()) ELSE transactions.confirmed_at END
RETURNING id, network_id, provider_id, hash, block_number, block_hash, block_timestamp, from_address, to_address, status, confirmations, fee_native, fee_details, external_tx_id, raw, first_seen_at, confirmed_at
`

type UpsertTransactionParams struct {
	NetworkID      int16
	ProviderID     int16
	Hash           string
	BlockNumber    pgtype.Int8
	BlockHash      *string
	BlockTimestamp *time.Time
	FromAddress    *string
	ToAddress      *string
	Status         TxStatus
	Confirmations  int32
	FeeNative      pgtype.Numeric
	FeeDetails     []byte
	ExternalTxID   *string
	Raw            []byte
}

// Transactions ----------------------------------------------------------------
func (q *Queries) UpsertTransaction(ctx context.Context, arg UpsertTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, upsertTransaction,
		arg.NetworkID,
		arg.ProviderID,
		arg.Hash,
		arg.BlockNumber,
		arg.BlockHash,
		arg.BlockTimestamp,
		arg.FromAddress,
		arg.ToAddress,
		arg.Status,
		arg.Confirmations,
		arg.FeeNative,
		arg.FeeDetails,
		arg.ExternalTxID,
		arg.Raw,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.NetworkID,
		&i.ProviderID,
		&i.Hash,
		&i.BlockNumber,
		&i.BlockHash,
		&i.BlockTimestamp,
		&i.FromAddress,
		&i.ToAddress,
		&i.Status,
		&i.Confirmations,
		&i.FeeNative,
		&i.FeeDetails,
		&i.ExternalTxID,
		&i.Raw,
		&i.FirstSeenAt,
		&i.ConfirmedAt,
	)
	return i, err
}
