// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checkout.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addInvoicePaymentOptionPaid = `-- name: AddInvoicePaymentOptionPaid :one
UPDATE invoice_payment_options
SET amount_paid = amount_paid + $2
WHERE id = $1
RETURNING id, invoice_id, asset_id, provider_id, address_id, memo, amount_due, amount_paid, exchange_rate, source_rate, spread_bps, rate_id, rate_locked_until, is_selected, selected_at, created_at
`

type AddInvoicePaymentOptionPaidParams struct {
	ID         uuid.UUID
	AmountPaid pgtype.Numeric
}

func (q *Queries) AddInvoicePaymentOptionPaid(ctx context.Context, arg AddInvoicePaymentOptionPaidParams) (InvoicePaymentOption, error) {
	row := q.db.QueryRow(ctx, addInvoicePaymentOptionPaid, arg.ID, arg.AmountPaid)
	var i InvoicePaymentOption
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.AssetID,
		&i.ProviderID,
		&i.AddressID,
		&i.Memo,
		&i.AmountDue,
		&i.AmountPaid,
		&i.ExchangeRate,
		&i.SourceRate,
		&i.SpreadBps,
		&i.RateID,
		&i.RateLockedUntil,
		&i.IsSelected,
		&i.SelectedAt,
		&i.CreatedAt,
	)
	return i, err
}

const cancelInvoice = `-- name: CancelInvoice :execrows
UPDATE invoices SET status = 'cancelled'
WHERE id = $1 AND organization_id = $2 AND status IN ('new', 'expired')
`

type CancelInvoiceParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) CancelInvoice(ctx context.Context, arg CancelInvoiceParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelInvoice, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countInvoicesByStatus = `-- name: CountInvoicesByStatus :many
SELECT status, count(*) AS count
FROM invoices
WHERE organization_id = $1
GROUP BY status
`

type CountInvoicesByStatusRow struct {
	Status InvoiceStatus
	Count  int64
}

func (q *Queries) CountInvoicesByStatus(ctx context.Context, organizationID uuid.UUID) ([]CountInvoicesByStatusRow, error) {
	rows, err := q.db.Query(ctx, countInvoicesByStatus, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountInvoicesByStatusRow{}
	for rows.Next() {
		var i CountInvoicesByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createInvoice = `-- name: CreateInvoice :one

INSERT INTO invoices (organization_id, external_id, price_currency, price_amount, description, customer_email, callback_url, return_url, metadata, expires_at, created_by_api_key)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, organization_id, external_id, price_currency, price_amount, status, description, customer_email, callback_url, return_url, metadata, expires_at, paid_at, confirmed_at, completed_at, created_by_api_key, created_at, updated_at
`

type CreateInvoiceParams struct {
	OrganizationID  uuid.UUID
	ExternalID      *string
	PriceCurrency   string
	PriceAmount     pgtype.Numeric
	Description     *string
	CustomerEmail   *string
	CallbackUrl     *string
	ReturnUrl       *string
	Metadata        []byte
	ExpiresAt       time.Time
	CreatedByApiKey uuid.NullUUID
}

// Checkout: invoices and the payment options quoted on them.
// Owned by internal/checkout.
func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.OrganizationID,
		arg.ExternalID,
		arg.PriceCurrency,
		arg.PriceAmount,
		arg.Description,
		arg.CustomerEmail,
		arg.CallbackUrl,
		arg.ReturnUrl,
		arg.Metadata,
		arg.ExpiresAt,
		arg.CreatedByApiKey,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ExternalID,
		&i.PriceCurrency,
		&i.PriceAmount,
		&i.Status,
		&i.Description,
		&i.CustomerEmail,
		&i.CallbackUrl,
		&i.ReturnUrl,
		&i.Metadata,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.ConfirmedAt,
		&i.CompletedAt,
		&i.CreatedByApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInvoicePaymentOption = `-- name: CreateInvoicePaymentOption :one

INSERT INTO invoice_payment_options (invoice_id, asset_id, provider_id, amount_due, exchange_rate, source_rate, spread_bps, rate_id, rate_locked_until)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, invoice_id, asset_id, provider_id, address_id, memo, amount_due, amount_paid, exchange_rate, source_rate, spread_bps, rate_id, rate_locked_until, is_selected, selected_at, created_at
`

type CreateInvoicePaymentOptionParams struct {
	InvoiceID       uuid.UUID
	AssetID         int16
	ProviderID      int16
	AmountDue       pgtype.Numeric
	ExchangeRate    pgtype.Numeric
	SourceRate      pgtype.Numeric
	SpreadBps       pgtype.Int4
	RateID          pgtype.Int8
	RateLockedUntil *time.Time
}

// Payment options ---------------------------------------------------------------
func (q *Queries) CreateInvoicePaymentOption(ctx context.Context, arg CreateInvoicePaymentOptionParams) (InvoicePaymentOption, error) {
	row := q.db.QueryRow(ctx, createInvoicePaymentOption,
		arg.InvoiceID,
		arg.AssetID,
		arg.ProviderID,
		arg.AmountDue,
		arg.ExchangeRate,
		arg.SourceRate,
		arg.SpreadBps,
		arg.RateID,
		arg.RateLockedUntil,
	)
	var i InvoicePaymentOption
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.AssetID,
		&i.ProviderID,
		&i.AddressID,
		&i.Memo,
		&i.AmountDue,
		&i.AmountPaid,
		&i.ExchangeRate,
		&i.SourceRate,
		&i.SpreadBps,
		&i.RateID,
		&i.RateLockedUntil,
		&i.IsSelected,
		&i.SelectedAt,
		&i.CreatedAt,
	)
	return i, err
}

const expireInvoices = `-- name: ExpireInvoices :many
UPDATE invoices SET status = 'expired'
WHERE status = 'new' AND expires_at <= now()
RETURNING id, organization_id, external_id, price_currency, price_amount, status, description, customer_email, callback_url, return_url, metadata, expires_at, paid_at, confirmed_at, completed_at, created_by_api_key, created_at, updated_at
`

func (q *Queries) ExpireInvoices(ctx context.Context) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, expireInvoices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invoice{}
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ExternalID,
			&i.PriceCurrency,
			&i.PriceAmount,
			&i.Status,
			&i.Description,
			&i.CustomerEmail,
			&i.CallbackUrl,
			&i.ReturnUrl,
			&i.Metadata,
			&i.ExpiresAt,
			&i.PaidAt,
			&i.ConfirmedAt,
			&i.CompletedAt,
			&i.CreatedByApiKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const extendInvoiceExpiry = `-- name: ExtendInvoiceExpiry :exec
UPDATE invoices SET expires_at = $2 WHERE id = $1
`

type ExtendInvoiceExpiryParams struct {
	ID        uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) ExtendInvoiceExpiry(ctx context.Context, arg ExtendInvoiceExpiryParams) error {
	_, err := q.db.Exec(ctx, extendInvoiceExpiry, arg.ID, arg.ExpiresAt)
	return err
}

const findOpenInvoiceOptionByAddress = `-- name: FindOpenInvoiceOptionByAddress :one
SELECT o.id, o.invoice_id, o.asset_id, o.provider_id, o.address_id, o.memo, o.amount_due, o.amount_paid, o.exchange_rate, o.source_rate, o.spread_bps, o.rate_id, o.rate_locked_until, o.is_selected, o.selected_at, o.created_at, i.id, i.organization_id, i.external_id, i.price_currency, i.price_amount, i.status, i.description, i.customer_email, i.callback_url, i.return_url, i.metadata, i.expires_at, i.paid_at, i.confirmed_at, i.completed_at, i.created_by_api_key, i.created_at, i.updated_at
FROM invoice_payment_options o
JOIN invoices i ON i.id = o.invoice_id
WHERE o.address_id = $1
  AND o.asset_id = $2
  AND i.status IN ('new', 'partial', 'paid', 'confirmed', 'expired')
ORDER BY i.created_at DESC
LIMIT 1
`

type FindOpenInvoiceOptionByAddressParams struct {
	AddressID uuid.NullUUID
	AssetID   int16
}

type FindOpenInvoiceOptionByAddressRow struct {
	InvoicePaymentOption InvoicePaymentOption
	Invoice              Invoice
}

// Deposit matching: which open invoice option owns this address?
func (q *Queries) FindOpenInvoiceOptionByAddress(ctx context.Context, arg FindOpenInvoiceOptionByAddressParams) (FindOpenInvoiceOptionByAddressRow, error) {
	row := q.db.QueryRow(ctx, findOpenInvoiceOptionByAddress, arg.AddressID, arg.AssetID)
	var i FindOpenInvoiceOptionByAddressRow
	err := row.Scan(
		&i.InvoicePaymentOption.ID,
		&i.InvoicePaymentOption.InvoiceID,
		&i.InvoicePaymentOption.AssetID,
		&i.InvoicePaymentOption.ProviderID,
		&i.InvoicePaymentOption.AddressID,
		&i.InvoicePaymentOption.Memo,
		&i.InvoicePaymentOption.AmountDue,
		&i.InvoicePaymentOption.AmountPaid,
		&i.InvoicePaymentOption.ExchangeRate,
		&i.InvoicePaymentOption.SourceRate,
		&i.InvoicePaymentOption.SpreadBps,
		&i.InvoicePaymentOption.RateID,
		&i.InvoicePaymentOption.RateLockedUntil,
		&i.InvoicePaymentOption.IsSelected,
		&i.InvoicePaymentOption.SelectedAt,
		&i.InvoicePaymentOption.CreatedAt,
		&i.Invoice.ID,
		&i.Invoice.OrganizationID,
		&i.Invoice.ExternalID,
		&i.Invoice.PriceCurrency,
		&i.Invoice.PriceAmount,
		&i.Invoice.Status,
		&i.Invoice.Description,
		&i.Invoice.CustomerEmail,
		&i.Invoice.CallbackUrl,
		&i.Invoice.ReturnUrl,
		&i.Invoice.Metadata,
		&i.Invoice.ExpiresAt,
		&i.Invoice.PaidAt,
		&i.Invoice.ConfirmedAt,
		&i.Invoice.CompletedAt,
		&i.Invoice.CreatedByApiKey,
		&i.Invoice.CreatedAt,
		&i.Invoice.UpdatedAt,
	)
	return i, err
}

const getInvoice = `-- name: GetInvoice :one
SELECT id, organization_id, external_id, price_currency, price_amount, status, description, customer_email, callback_url, return_url, metadata, expires_at, paid_at, confirmed_at, completed_at, created_by_api_key, created_at, updated_at FROM invoices WHERE id = $1
`

func (q *Queries) GetInvoice(ctx context.Context, id uuid.UUID) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoice, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ExternalID,
		&i.PriceCurrency,
		&i.PriceAmount,
		&i.Status,
		&i.Description,
		&i.CustomerEmail,
		&i.CallbackUrl,
		&i.ReturnUrl,
		&i.Metadata,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.ConfirmedAt,
		&i.CompletedAt,
		&i.CreatedByApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvoiceByExternalID = `-- name: GetInvoiceByExternalID :one
SELECT id, organization_id, external_id, price_currency, price_amount, status, description, customer_email, callback_url, return_url, metadata, expires_at, paid_at, confirmed_at, completed_at, created_by_api_key, created_at, updated_at FROM invoices WHERE organization_id = $1 AND external_id = $2
`

type GetInvoiceByExternalIDParams struct {
	OrganizationID uuid.UUID
	ExternalID     *string
}

func (q *Queries) GetInvoiceByExternalID(ctx context.Context, arg GetInvoiceByExternalIDParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceByExternalID, arg.OrganizationID, arg.ExternalID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ExternalID,
		&i.PriceCurrency,
		&i.PriceAmount,
		&i.Status,
		&i.Description,
		&i.CustomerEmail,
		&i.CallbackUrl,
		&i.ReturnUrl,
		&i.Metadata,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.ConfirmedAt,
		&i.CompletedAt,
		&i.CreatedByApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvoiceForOrganization = `-- name: GetInvoiceForOrganization :one
SELECT id, organization_id, external_id, price_currency, price_amount, status, description, customer_email, callback_url, return_url, metadata, expires_at, paid_at, confirmed_at, completed_at, created_by_api_key, created_at, updated_at FROM invoices WHERE id = $1 AND organization_id = $2
`

type GetInvoiceForOrganizationParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) GetInvoiceForOrganization(ctx context.Context, arg GetInvoiceForOrganizationParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceForOrganization, arg.ID, arg.OrganizationID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ExternalID,
		&i.PriceCurrency,
		&i.PriceAmount,
		&i.Status,
		&i.Description,
		&i.CustomerEmail,
		&i.CallbackUrl,
		&i.ReturnUrl,
		&i.Metadata,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.ConfirmedAt,
		&i.CompletedAt,
		&i.CreatedByApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvoicePaymentOption = `-- name: GetInvoicePaymentOption :one
SELECT id, invoice_id, asset_id, provider_id, address_id, memo, amount_due, amount_paid, exchange_rate, source_rate, spread_bps, rate_id, rate_locked_until, is_selected, selected_at, created_at FROM invoice_payment_options WHERE id = $1
`

func (q *Queries) GetInvoicePaymentOption(ctx context.Context, id uuid.UUID) (InvoicePaymentOption, error) {
	row := q.db.QueryRow(ctx, getInvoicePaymentOption, id)
	var i InvoicePaymentOption
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.AssetID,
		&i.ProviderID,
		&i.AddressID,
		&i.Memo,
		&i.AmountDue,
		&i.AmountPaid,
		&i.ExchangeRate,
		&i.SourceRate,
		&i.SpreadBps,
		&i.RateID,
		&i.RateLockedUntil,
		&i.IsSelected,
		&i.SelectedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInvoicePaymentOptionByAsset = `-- name: GetInvoicePaymentOptionByAsset :one
SELECT id, invoice_id, asset_id, provider_id, address_id, memo, amount_due, amount_paid, exchange_rate, source_rate, spread_bps, rate_id, rate_locked_until, is_selected, selected_at, created_at FROM invoice_payment_options WHERE invoice_id = $1 AND asset_id = $2
`

type GetInvoicePaymentOptionByAssetParams struct {
	InvoiceID uuid.UUID
	AssetID   int16
}

func (q *Queries) GetInvoicePaymentOptionByAsset(ctx context.Context, arg GetInvoicePaymentOptionByAssetParams) (InvoicePaymentOption, error) {
	row := q.db.QueryRow(ctx, getInvoicePaymentOptionByAsset, arg.InvoiceID, arg.AssetID)
	var i InvoicePaymentOption
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.AssetID,
		&i.ProviderID,
		&i.AddressID,
		&i.Memo,
		&i.AmountDue,
		&i.AmountPaid,
		&i.ExchangeRate,
		&i.SourceRate,
		&i.SpreadBps,
		&i.RateID,
		&i.RateLockedUntil,
		&i.IsSelected,
		&i.SelectedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSelectedInvoicePaymentOption = `-- name: GetSelectedInvoicePaymentOption :one
SELECT id, invoice_id, asset_id, provider_id, address_id, memo, amount_due, amount_paid, exchange_rate, source_rate, spread_bps, rate_id, rate_locked_until, is_selected, selected_at, created_at FROM invoice_payment_options WHERE invoice_id = $1 AND is_selected
`

func (q *Queries) GetSelectedInvoicePaymentOption(ctx context.Context, invoiceID uuid.UUID) (InvoicePaymentOption, error) {
	row := q.db.QueryRow(ctx, getSelectedInvoicePaymentOption, invoiceID)
	var i InvoicePaymentOption
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.AssetID,
		&i.ProviderID,
		&i.AddressID,
		&i.Memo,
		&i.AmountDue,
		&i.AmountPaid,
		&i.ExchangeRate,
		&i.SourceRate,
		&i.SpreadBps,
		&i.RateID,
		&i.RateLockedUntil,
		&i.IsSelected,
		&i.SelectedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listInvoicePaymentOptions = `-- name: ListInvoicePaymentOptions :many
SELECT o.id, o.invoice_id, o.asset_id, o.provider_id, o.address_id, o.memo, o.amount_due, o.amount_paid, o.exchange_rate, o.source_rate, o.spread_bps, o.rate_id, o.rate_locked_until, o.is_selected, o.selected_at, o.created_at, a.id, a.network_id, a.code, a.symbol, a.name, a.kind, a.token_standard, a.contract_address, a.decimals, a.is_stablecoin, a.logo_url, a.min_deposit, a.min_withdrawal, a.is_enabled, n.code AS network_code, n.name AS network_name, addr.address, addr.memo AS address_memo
FROM invoice_payment_options o
JOIN assets a        ON a.id = o.asset_id
JOIN networks n      ON n.id = a.network_id
LEFT JOIN addresses addr ON addr.id = o.address_id
WHERE o.invoice_id = $1
ORDER BY n.code, a.code
`

type ListInvoicePaymentOptionsRow struct {
	InvoicePaymentOption InvoicePaymentOption
	Asset                Asset
	NetworkCode          string
	NetworkName          string
	Address              *string
	AddressMemo          *string
}

func (q *Queries) ListInvoicePaymentOptions(ctx context.Context, invoiceID uuid.UUID) ([]ListInvoicePaymentOptionsRow, error) {
	rows, err := q.db.Query(ctx, listInvoicePaymentOptions, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoicePaymentOptionsRow{}
	for rows.Next() {
		var i ListInvoicePaymentOptionsRow
		if err := rows.Scan(
			&i.InvoicePaymentOption.ID,
			&i.InvoicePaymentOption.InvoiceID,
			&i.InvoicePaymentOption.AssetID,
			&i.InvoicePaymentOption.ProviderID,
			&i.InvoicePaymentOption.AddressID,
			&i.InvoicePaymentOption.Memo,
			&i.InvoicePaymentOption.AmountDue,
			&i.InvoicePaymentOption.AmountPaid,
			&i.InvoicePaymentOption.ExchangeRate,
			&i.InvoicePaymentOption.SourceRate,
			&i.InvoicePaymentOption.SpreadBps,
			&i.InvoicePaymentOption.RateID,
			&i.InvoicePaymentOption.RateLockedUntil,
			&i.InvoicePaymentOption.IsSelected,
			&i.InvoicePaymentOption.SelectedAt,
			&i.InvoicePaymentOption.CreatedAt,
			&i.Asset.ID,
			&i.Asset.NetworkID,
			&i.Asset.Code,
			&i.Asset.Symbol,
			&i.Asset.Name,
			&i.Asset.Kind,
			&i.Asset.TokenStandard,
			&i.Asset.ContractAddress,
			&i.Asset.Decimals,
			&i.Asset.IsStablecoin,
			&i.Asset.LogoUrl,
			&i.Asset.MinDeposit,
			&i.Asset.MinWithdrawal,
			&i.Asset.IsEnabled,
			&i.NetworkCode,
			&i.NetworkName,
			&i.Address,
			&i.AddressMemo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoices = `-- name: ListInvoices :many
SELECT id, organization_id, external_id, price_currency, price_amount, status, description, customer_email, callback_url, return_url, metadata, expires_at, paid_at, confirmed_at, completed_at, created_by_api_key, created_at, updated_at FROM invoices
WHERE organization_id = $1
  AND (status = $4 OR $4 IS NULL)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListInvoicesParams struct {
	OrganizationID uuid.UUID
	Limit          int32
	Offset         int32
	Status         NullInvoiceStatus
}

func (q *Queries) ListInvoices(ctx context.Context, arg ListInvoicesParams) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, listInvoices,
		arg.OrganizationID,
		arg.Limit,
		arg.Offset,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invoice{}
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ExternalID,
			&i.PriceCurrency,
			&i.PriceAmount,
			&i.Status,
			&i.Description,
			&i.CustomerEmail,
			&i.CallbackUrl,
			&i.ReturnUrl,
			&i.Metadata,
			&i.ExpiresAt,
			&i.PaidAt,
			&i.ConfirmedAt,
			&i.CompletedAt,
			&i.CreatedByApiKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requoteInvoicePaymentOption = `-- name: RequoteInvoicePaymentOption :one
UPDATE invoice_payment_options
SET amount_due = $2, exchange_rate = $3, source_rate = $4, spread_bps = $5, rate_id = $6, rate_locked_until = $7
WHERE id = $1
RETURNING id, invoice_id, asset_id, provider_id, address_id, memo, amount_due, amount_paid, exchange_rate, source_rate, spread_bps, rate_id, rate_locked_until, is_selected, selected_at, created_at
`

type RequoteInvoicePaymentOptionParams struct {
	ID              uuid.UUID
	AmountDue       pgtype.Numeric
	ExchangeRate    pgtype.Numeric
	SourceRate      pgtype.Numeric
	SpreadBps       pgtype.Int4
	RateID          pgtype.Int8
	RateLockedUntil *time.Time
}

func (q *Queries) RequoteInvoicePaymentOption(ctx context.Context, arg RequoteInvoicePaymentOptionParams) (InvoicePaymentOption, error) {
	row := q.db.QueryRow(ctx, requoteInvoicePaymentOption,
		arg.ID,
		arg.AmountDue,
		arg.ExchangeRate,
		arg.SourceRate,
		arg.SpreadBps,
		arg.RateID,
		arg.RateLockedUntil,
	)
	var i InvoicePaymentOption
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.AssetID,
		&i.ProviderID,
		&i.AddressID,
		&i.Memo,
		&i.AmountDue,
		&i.AmountPaid,
		&i.ExchangeRate,
		&i.SourceRate,
		&i.SpreadBps,
		&i.RateID,
		&i.RateLockedUntil,
		&i.IsSelected,
		&i.SelectedAt,
		&i.CreatedAt,
	)
	return i, err
}

const selectInvoicePaymentOption = `-- name: SelectInvoicePaymentOption :one
UPDATE invoice_payment_options
SET address_id        = $2,
    memo              = $3,
    is_selected       = TRUE,
    selected_at       = now(),
    rate_locked_until = $4
WHERE id = $1
RETURNING id, invoice_id, asset_id, provider_id, address_id, memo, amount_due, amount_paid, exchange_rate, source_rate, spread_bps, rate_id, rate_locked_until, is_selected, selected_at, created_at
`

type SelectInvoicePaymentOptionParams struct {
	ID              uuid.UUID
	AddressID       uuid.NullUUID
	Memo            *string
	RateLockedUntil *time.Time
}

func (q *Queries) SelectInvoicePaymentOption(ctx context.Context, arg SelectInvoicePaymentOptionParams) (InvoicePaymentOption, error) {
	row := q.db.QueryRow(ctx, selectInvoicePaymentOption,
		arg.ID,
		arg.AddressID,
		arg.Memo,
		arg.RateLockedUntil,
	)
	var i InvoicePaymentOption
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.AssetID,
		&i.ProviderID,
		&i.AddressID,
		&i.Memo,
		&i.AmountDue,
		&i.AmountPaid,
		&i.ExchangeRate,
		&i.SourceRate,
		&i.SpreadBps,
		&i.RateID,
		&i.RateLockedUntil,
		&i.IsSelected,
		&i.SelectedAt,
		&i.CreatedAt,
	)
	return i, err
}

const setInvoiceStatus = `-- name: SetInvoiceStatus :one
UPDATE invoices
SET status       = $2::invoice_status,
    paid_at      = CASE WHEN $2::invoice_status IN ('paid', 'confirmed', 'completed') THEN COALESCE(paid_at, now())      ELSE paid_at      END,
    confirmed_at = CASE WHEN $2::invoice_status IN ('confirmed', 'completed')         THEN COALESCE(confirmed_at, now()) ELSE confirmed_at END,
    completed_at = CASE WHEN $2::invoice_status = 'completed'                          THEN COALESCE(completed_at, now()) ELSE completed_at END
WHERE id = $1
RETURNING id, organization_id, external_id, price_currency, price_amount, status, description, customer_email, callback_url, return_url, metadata, expires_at, paid_at, confirmed_at, completed_at, created_by_api_key, created_at, updated_at
`

type SetInvoiceStatusParams struct {
	ID     uuid.UUID
	Status InvoiceStatus
}

func (q *Queries) SetInvoiceStatus(ctx context.Context, arg SetInvoiceStatusParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, setInvoiceStatus, arg.ID, arg.Status)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ExternalID,
		&i.PriceCurrency,
		&i.PriceAmount,
		&i.Status,
		&i.Description,
		&i.CustomerEmail,
		&i.CallbackUrl,
		&i.ReturnUrl,
		&i.Metadata,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.ConfirmedAt,
		&i.CompletedAt,
		&i.CreatedByApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
