// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const confirmPayment = `-- name: ConfirmPayment :one
UPDATE payments
SET status = 'confirmed', confirmed_at = COALESCE(confirmed_at, now())
WHERE id = $1 AND status = 'detected'
RETURNING id, organization_id, invoice_id, option_id, address_id, asset_id, provider_id, transfer_id, amount, fee_amount, fee_bps_applied, spread_amount, network_fee_amount, status, detected_at, confirmed_at, credited_at, created_at, updated_at, fee_schedule_id
`

func (q *Queries) ConfirmPayment(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, confirmPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InvoiceID,
		&i.OptionID,
		&i.AddressID,
		&i.AssetID,
		&i.ProviderID,
		&i.TransferID,
		&i.Amount,
		&i.FeeAmount,
		&i.FeeBpsApplied,
		&i.SpreadAmount,
		&i.NetworkFeeAmount,
		&i.Status,
		&i.DetectedAt,
		&i.ConfirmedAt,
		&i.CreditedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FeeScheduleID,
	)
	return i, err
}

const countPaymentsByDayAndStatus = `-- name: CountPaymentsByDayAndStatus :many
SELECT (created_at AT TIME ZONE 'UTC')::date AS day, status, count(*) AS count
FROM payments
WHERE organization_id = $1 AND created_at >= $2
GROUP BY 1, 2
ORDER BY 1
`

type CountPaymentsByDayAndStatusParams struct {
	OrganizationID uuid.UUID
	CreatedAt      time.Time
}

type CountPaymentsByDayAndStatusRow struct {
	Day    pgtype.Date
	Status PaymentStatus
	Count  int64
}

func (q *Queries) CountPaymentsByDayAndStatus(ctx context.Context, arg CountPaymentsByDayAndStatusParams) ([]CountPaymentsByDayAndStatusRow, error) {
	rows, err := q.db.Query(ctx, countPaymentsByDayAndStatus, arg.OrganizationID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountPaymentsByDayAndStatusRow{}
	for rows.Next() {
		var i CountPaymentsByDayAndStatusRow
		if err := rows.Scan(&i.Day, &i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPaymentsByNetwork = `-- name: CountPaymentsByNetwork :many
SELECT n.code AS network_code, n.name AS network_name, count(*) AS count
FROM payments p
JOIN assets a   ON a.id = p.asset_id
JOIN networks n ON n.id = a.network_id
WHERE p.organization_id = $1 AND p.created_at >= $2
GROUP BY n.code, n.name
ORDER BY count DESC
`

type CountPaymentsByNetworkParams struct {
	OrganizationID uuid.UUID
	CreatedAt      time.Time
}

type CountPaymentsByNetworkRow struct {
	NetworkCode string
	NetworkName string
	Count       int64
}

func (q *Queries) CountPaymentsByNetwork(ctx context.Context, arg CountPaymentsByNetworkParams) ([]CountPaymentsByNetworkRow, error) {
	rows, err := q.db.Query(ctx, countPaymentsByNetwork, arg.OrganizationID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountPaymentsByNetworkRow{}
	for rows.Next() {
		var i CountPaymentsByNetworkRow
		if err := rows.Scan(&i.NetworkCode, &i.NetworkName, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPaymentsByStatus = `-- name: CountPaymentsByStatus :many
SELECT status, count(*) AS count
FROM payments
WHERE organization_id = $1
GROUP BY status
`

type CountPaymentsByStatusRow struct {
	Status PaymentStatus
	Count  int64
}

func (q *Queries) CountPaymentsByStatus(ctx context.Context, organizationID uuid.UUID) ([]CountPaymentsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countPaymentsByStatus, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountPaymentsByStatusRow{}
	for rows.Next() {
		var i CountPaymentsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPaymentsSince = `-- name: CountPaymentsSince :one
SELECT count(*) FROM payments WHERE organization_id = $1 AND created_at >= $2
`

type CountPaymentsSinceParams struct {
	OrganizationID uuid.UUID
	CreatedAt      time.Time
}

func (q *Queries) CountPaymentsSince(ctx context.Context, arg CountPaymentsSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentsSince, arg.OrganizationID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPayment = `-- name: CreatePayment :one

INSERT INTO payments (organization_id, invoice_id, option_id, address_id, asset_id, provider_id, transfer_id, amount,
                      fee_amount, fee_bps_applied, spread_amount, network_fee_amount, fee_schedule_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, organization_id, invoice_id, option_id, address_id, asset_id, provider_id, transfer_id, amount, fee_amount, fee_bps_applied, spread_amount, network_fee_amount, status, detected_at, confirmed_at, credited_at, created_at, updated_at, fee_schedule_id
`

type CreatePaymentParams struct {
	OrganizationID   uuid.UUID
	InvoiceID        uuid.NullUUID
	OptionID         uuid.NullUUID
	AddressID        uuid.UUID
	AssetID          int16
	ProviderID       int16
	TransferID       uuid.UUID
	Amount           pgtype.Numeric
	FeeAmount        pgtype.Numeric
	FeeBpsApplied    pgtype.Int4
	SpreadAmount     pgtype.Numeric
	NetworkFeeAmount pgtype.Numeric
	FeeScheduleID    uuid.NullUUID
}

// Payments: an on-chain transfer matched to a merchant, moving
// detected -> confirmed -> credited (or reverted). Owned by internal/payments.
func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.OrganizationID,
		arg.InvoiceID,
		arg.OptionID,
		arg.AddressID,
		arg.AssetID,
		arg.ProviderID,
		arg.TransferID,
		arg.Amount,
		arg.FeeAmount,
		arg.FeeBpsApplied,
		arg.SpreadAmount,
		arg.NetworkFeeAmount,
		arg.FeeScheduleID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InvoiceID,
		&i.OptionID,
		&i.AddressID,
		&i.AssetID,
		&i.ProviderID,
		&i.TransferID,
		&i.Amount,
		&i.FeeAmount,
		&i.FeeBpsApplied,
		&i.SpreadAmount,
		&i.NetworkFeeAmount,
		&i.Status,
		&i.DetectedAt,
		&i.ConfirmedAt,
		&i.CreditedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FeeScheduleID,
	)
	return i, err
}

const creditPayment = `-- name: CreditPayment :one
UPDATE payments
SET status = 'credited', credited_at = COALESCE(credited_at, now())
WHERE id = $1 AND status IN ('detected', 'confirmed')
RETURNING id, organization_id, invoice_id, option_id, address_id, asset_id, provider_id, transfer_id, amount, fee_amount, fee_bps_applied, spread_amount, network_fee_amount, status, detected_at, confirmed_at, credited_at, created_at, updated_at, fee_schedule_id
`

func (q *Queries) CreditPayment(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, creditPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InvoiceID,
		&i.OptionID,
		&i.AddressID,
		&i.AssetID,
		&i.ProviderID,
		&i.TransferID,
		&i.Amount,
		&i.FeeAmount,
		&i.FeeBpsApplied,
		&i.SpreadAmount,
		&i.NetworkFeeAmount,
		&i.Status,
		&i.DetectedAt,
		&i.ConfirmedAt,
		&i.CreditedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FeeScheduleID,
	)
	return i, err
}

const getPayment = `-- name: GetPayment :one
SELECT id, organization_id, invoice_id, option_id, address_id, asset_id, provider_id, transfer_id, amount, fee_amount, fee_bps_applied, spread_amount, network_fee_amount, status, detected_at, confirmed_at, credited_at, created_at, updated_at, fee_schedule_id FROM payments WHERE id = $1
`

func (q *Queries) GetPayment(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InvoiceID,
		&i.OptionID,
		&i.AddressID,
		&i.AssetID,
		&i.ProviderID,
		&i.TransferID,
		&i.Amount,
		&i.FeeAmount,
		&i.FeeBpsApplied,
		&i.SpreadAmount,
		&i.NetworkFeeAmount,
		&i.Status,
		&i.DetectedAt,
		&i.ConfirmedAt,
		&i.CreditedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FeeScheduleID,
	)
	return i, err
}

const getPaymentByTransfer = `-- name: GetPaymentByTransfer :one
SELECT id, organization_id, invoice_id, option_id, address_id, asset_id, provider_id, transfer_id, amount, fee_amount, fee_bps_applied, spread_amount, network_fee_amount, status, detected_at, confirmed_at, credited_at, created_at, updated_at, fee_schedule_id FROM payments WHERE transfer_id = $1
`

func (q *Queries) GetPaymentByTransfer(ctx context.Context, transferID uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByTransfer, transferID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InvoiceID,
		&i.OptionID,
		&i.AddressID,
		&i.AssetID,
		&i.ProviderID,
		&i.TransferID,
		&i.Amount,
		&i.FeeAmount,
		&i.FeeBpsApplied,
		&i.SpreadAmount,
		&i.NetworkFeeAmount,
		&i.Status,
		&i.DetectedAt,
		&i.ConfirmedAt,
		&i.CreditedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FeeScheduleID,
	)
	return i, err
}

const getPaymentForOrganization = `-- name: GetPaymentForOrganization :one
SELECT id, organization_id, invoice_id, option_id, address_id, asset_id, provider_id, transfer_id, amount, fee_amount, fee_bps_applied, spread_amount, network_fee_amount, status, detected_at, confirmed_at, credited_at, created_at, updated_at, fee_schedule_id FROM payments WHERE id = $1 AND organization_id = $2
`

type GetPaymentForOrganizationParams struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
}

func (q *Queries) GetPaymentForOrganization(ctx context.Context, arg GetPaymentForOrganizationParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentForOrganization, arg.ID, arg.OrganizationID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InvoiceID,
		&i.OptionID,
		&i.AddressID,
		&i.AssetID,
		&i.ProviderID,
		&i.TransferID,
		&i.Amount,
		&i.FeeAmount,
		&i.FeeBpsApplied,
		&i.SpreadAmount,
		&i.NetworkFeeAmount,
		&i.Status,
		&i.DetectedAt,
		&i.ConfirmedAt,
		&i.CreditedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FeeScheduleID,
	)
	return i, err
}

const listDetectedPayments = `-- name: ListDetectedPayments :many
SELECT p.id, p.organization_id, p.invoice_id, p.option_id, p.address_id, p.asset_id, p.provider_id, p.transfer_id, p.amount, p.fee_amount, p.fee_bps_applied, p.spread_amount, p.network_fee_amount, p.status, p.detected_at, p.confirmed_at, p.credited_at, p.created_at, p.updated_at, p.fee_schedule_id, tx.status AS tx_status, tx.confirmations, n.required_confirmations
FROM payments p
JOIN transfers t     ON t.id = p.transfer_id
JOIN transactions tx ON tx.id = t.transaction_id
JOIN assets a        ON a.id = p.asset_id
JOIN networks n      ON n.id = a.network_id
WHERE p.status = 'detected'
ORDER BY p.detected_at
LIMIT $1
`

type ListDetectedPaymentsRow struct {
	Payment               Payment
	TxStatus              TxStatus
	Confirmations         int32
	RequiredConfirmations int32
}

// Detected payments whose transaction data may have moved on. The worker
// compares confirmations with the network threshold and confirms or reverts.
func (q *Queries) ListDetectedPayments(ctx context.Context, limit int32) ([]ListDetectedPaymentsRow, error) {
	rows, err := q.db.Query(ctx, listDetectedPayments, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDetectedPaymentsRow{}
	for rows.Next() {
		var i ListDetectedPaymentsRow
		if err := rows.Scan(
			&i.Payment.ID,
			&i.Payment.OrganizationID,
			&i.Payment.InvoiceID,
			&i.Payment.OptionID,
			&i.Payment.AddressID,
			&i.Payment.AssetID,
			&i.Payment.ProviderID,
			&i.Payment.TransferID,
			&i.Payment.Amount,
			&i.Payment.FeeAmount,
			&i.Payment.FeeBpsApplied,
			&i.Payment.SpreadAmount,
			&i.Payment.NetworkFeeAmount,
			&i.Payment.Status,
			&i.Payment.DetectedAt,
			&i.Payment.ConfirmedAt,
			&i.Payment.CreditedAt,
			&i.Payment.CreatedAt,
			&i.Payment.UpdatedAt,
			&i.Payment.FeeScheduleID,
			&i.TxStatus,
			&i.Confirmations,
			&i.RequiredConfirmations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayments = `-- name: ListPayments :many
SELECT p.id, p.organization_id, p.invoice_id, p.option_id, p.address_id, p.asset_id, p.provider_id, p.transfer_id, p.amount, p.fee_amount, p.fee_bps_applied, p.spread_amount, p.network_fee_amount, p.status, p.detected_at, p.confirmed_at, p.credited_at, p.created_at, p.updated_at, p.fee_schedule_id, a.id, a.network_id, a.code, a.symbol, a.name, a.kind, a.token_standard, a.contract_address, a.decimals, a.is_stablecoin, a.logo_url, a.min_deposit, a.min_withdrawal, a.is_enabled, tx.hash AS tx_hash, tx.confirmations, n.required_confirmations, n.code AS network_code, i.customer_email
FROM payments p
JOIN assets a         ON a.id = p.asset_id
JOIN networks n       ON n.id = a.network_id
JOIN transfers t      ON t.id = p.transfer_id
JOIN transactions tx  ON tx.id = t.transaction_id
LEFT JOIN invoices i  ON i.id = p.invoice_id
WHERE p.organization_id = $1
  AND (p.status = $4 OR $4 IS NULL)
ORDER BY p.created_at DESC
LIMIT $2 OFFSET $3
`

type ListPaymentsParams struct {
	OrganizationID uuid.UUID
	Limit          int32
	Offset         int32
	Status         NullPaymentStatus
}

type ListPaymentsRow struct {
	Payment               Payment
	Asset                 Asset
	TxHash                string
	Confirmations         int32
	RequiredConfirmations int32
	NetworkCode           string
	CustomerEmail         *string
}

func (q *Queries) ListPayments(ctx context.Context, arg ListPaymentsParams) ([]ListPaymentsRow, error) {
	rows, err := q.db.Query(ctx, listPayments,
		arg.OrganizationID,
		arg.Limit,
		arg.Offset,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaymentsRow{}
	for rows.Next() {
		var i ListPaymentsRow
		if err := rows.Scan(
			&i.Payment.ID,
			&i.Payment.OrganizationID,
			&i.Payment.InvoiceID,
			&i.Payment.OptionID,
			&i.Payment.AddressID,
			&i.Payment.AssetID,
			&i.Payment.ProviderID,
			&i.Payment.TransferID,
			&i.Payment.Amount,
			&i.Payment.FeeAmount,
			&i.Payment.FeeBpsApplied,
			&i.Payment.SpreadAmount,
			&i.Payment.NetworkFeeAmount,
			&i.Payment.Status,
			&i.Payment.DetectedAt,
			&i.Payment.ConfirmedAt,
			&i.Payment.CreditedAt,
			&i.Payment.CreatedAt,
			&i.Payment.UpdatedAt,
			&i.Payment.FeeScheduleID,
			&i.Asset.ID,
			&i.Asset.NetworkID,
			&i.Asset.Code,
			&i.Asset.Symbol,
			&i.Asset.Name,
			&i.Asset.Kind,
			&i.Asset.TokenStandard,
			&i.Asset.ContractAddress,
			&i.Asset.Decimals,
			&i.Asset.IsStablecoin,
			&i.Asset.LogoUrl,
			&i.Asset.MinDeposit,
			&i.Asset.MinWithdrawal,
			&i.Asset.IsEnabled,
			&i.TxHash,
			&i.Confirmations,
			&i.RequiredConfirmations,
			&i.NetworkCode,
			&i.CustomerEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsForInvoice = `-- name: ListPaymentsForInvoice :many
SELECT id, organization_id, invoice_id, option_id, address_id, asset_id, provider_id, transfer_id, amount, fee_amount, fee_bps_applied, spread_amount, network_fee_amount, status, detected_at, confirmed_at, credited_at, created_at, updated_at, fee_schedule_id FROM payments WHERE invoice_id = $1 ORDER BY created_at
`

func (q *Queries) ListPaymentsForInvoice(ctx context.Context, invoiceID uuid.NullUUID) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsForInvoice, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.InvoiceID,
			&i.OptionID,
			&i.AddressID,
			&i.AssetID,
			&i.ProviderID,
			&i.TransferID,
			&i.Amount,
			&i.FeeAmount,
			&i.FeeBpsApplied,
			&i.SpreadAmount,
			&i.NetworkFeeAmount,
			&i.Status,
			&i.DetectedAt,
			&i.ConfirmedAt,
			&i.CreditedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FeeScheduleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revertPayment = `-- name: RevertPayment :one
UPDATE payments
SET status = 'reverted'
WHERE id = $1 AND status IN ('detected', 'confirmed')
RETURNING id, organization_id, invoice_id, option_id, address_id, asset_id, provider_id, transfer_id, amount, fee_amount, fee_bps_applied, spread_amount, network_fee_amount, status, detected_at, confirmed_at, credited_at, created_at, updated_at, fee_schedule_id
`

func (q *Queries) RevertPayment(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, revertPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.InvoiceID,
		&i.OptionID,
		&i.AddressID,
		&i.AssetID,
		&i.ProviderID,
		&i.TransferID,
		&i.Amount,
		&i.FeeAmount,
		&i.FeeBpsApplied,
		&i.SpreadAmount,
		&i.NetworkFeeAmount,
		&i.Status,
		&i.DetectedAt,
		&i.ConfirmedAt,
		&i.CreditedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FeeScheduleID,
	)
	return i, err
}

const sumCreditedPayments = `-- name: SumCreditedPayments :one
SELECT COALESCE(SUM(amount), 0)::crypto_amount AS gross,
       COALESCE(SUM(fee_amount + spread_amount + network_fee_amount), 0)::crypto_amount AS fees
FROM payments
WHERE organization_id = $1 AND asset_id = $2 AND status = 'credited' AND credited_at >= $3
`

type SumCreditedPaymentsParams struct {
	OrganizationID uuid.UUID
	AssetID        int16
	CreditedAt     *time.Time
}

type SumCreditedPaymentsRow struct {
	Gross pgtype.Numeric
	Fees  pgtype.Numeric
}

func (q *Queries) SumCreditedPayments(ctx context.Context, arg SumCreditedPaymentsParams) (SumCreditedPaymentsRow, error) {
	row := q.db.QueryRow(ctx, sumCreditedPayments, arg.OrganizationID, arg.AssetID, arg.CreditedAt)
	var i SumCreditedPaymentsRow
	err := row.Scan(&i.Gross, &i.Fees)
	return i, err
}

const sumPaymentsByAsset = `-- name: SumPaymentsByAsset :many
SELECT p.asset_id, a.code AS asset_code, a.symbol, a.name AS asset_name, count(*) AS count,
       COALESCE(SUM(p.amount), 0)::crypto_amount AS amount,
       COALESCE(SUM(p.fee_amount + p.spread_amount + p.network_fee_amount), 0)::crypto_amount AS fees
FROM payments p
JOIN assets a ON a.id = p.asset_id
WHERE p.organization_id = $1 AND p.status IN ('confirmed', 'credited') AND p.created_at >= $2
GROUP BY p.asset_id, a.code, a.symbol, a.name
ORDER BY amount DESC
`

type SumPaymentsByAssetParams struct {
	OrganizationID uuid.UUID
	CreatedAt      time.Time
}

type SumPaymentsByAssetRow struct {
	AssetID   int16
	AssetCode string
	Symbol    string
	AssetName string
	Count     int64
	Amount    pgtype.Numeric
	Fees      pgtype.Numeric
}

func (q *Queries) SumPaymentsByAsset(ctx context.Context, arg SumPaymentsByAssetParams) ([]SumPaymentsByAssetRow, error) {
	rows, err := q.db.Query(ctx, sumPaymentsByAsset, arg.OrganizationID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumPaymentsByAssetRow{}
	for rows.Next() {
		var i SumPaymentsByAssetRow
		if err := rows.Scan(
			&i.AssetID,
			&i.AssetCode,
			&i.Symbol,
			&i.AssetName,
			&i.Count,
			&i.Amount,
			&i.Fees,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumPaymentsByDay = `-- name: SumPaymentsByDay :many

SELECT (created_at AT TIME ZONE 'UTC')::date AS day, asset_id, count(*) AS count, COALESCE(SUM(amount), 0)::crypto_amount AS amount
FROM payments
WHERE organization_id = $1 AND status IN ('confirmed', 'credited') AND created_at >= $2
GROUP BY 1, 2
ORDER BY 1
`

type SumPaymentsByDayParams struct {
	OrganizationID uuid.UUID
	CreatedAt      time.Time
}

type SumPaymentsByDayRow struct {
	Day     pgtype.Date
	AssetID int16
	Count   int64
	Amount  pgtype.Numeric
}

// Dashboard aggregates ----------------------------------------------------------
func (q *Queries) SumPaymentsByDay(ctx context.Context, arg SumPaymentsByDayParams) ([]SumPaymentsByDayRow, error) {
	rows, err := q.db.Query(ctx, sumPaymentsByDay, arg.OrganizationID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumPaymentsByDayRow{}
	for rows.Next() {
		var i SumPaymentsByDayRow
		if err := rows.Scan(
			&i.Day,
			&i.AssetID,
			&i.Count,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
