// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: treasury.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeInternalTransfer = `-- name: CompleteInternalTransfer :one
UPDATE internal_transfers
SET status = 'confirmed', energy_used = $2, bandwidth_used = $3, cost_native = $4
WHERE id = $1 AND status = 'broadcast'
RETURNING id, kind, asset_id, provider_id, from_address_id, to_address_id, amount, status, transaction_id, external_ref, energy_used, bandwidth_used, cost_native, failure_reason, created_at, updated_at
`

type CompleteInternalTransferParams struct {
	ID            uuid.UUID
	EnergyUsed    pgtype.Int8
	BandwidthUsed pgtype.Int8
	CostNative    pgtype.Numeric
}

func (q *Queries) CompleteInternalTransfer(ctx context.Context, arg CompleteInternalTransferParams) (InternalTransfer, error) {
	row := q.db.QueryRow(ctx, completeInternalTransfer,
		arg.ID,
		arg.EnergyUsed,
		arg.BandwidthUsed,
		arg.CostNative,
	)
	var i InternalTransfer
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.AssetID,
		&i.ProviderID,
		&i.FromAddressID,
		&i.ToAddressID,
		&i.Amount,
		&i.Status,
		&i.TransactionID,
		&i.ExternalRef,
		&i.EnergyUsed,
		&i.BandwidthUsed,
		&i.CostNative,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInternalTransfer = `-- name: CreateInternalTransfer :one

INSERT INTO internal_transfers (kind, asset_id, provider_id, from_address_id, to_address_id, amount)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, kind, asset_id, provider_id, from_address_id, to_address_id, amount, status, transaction_id, external_ref, energy_used, bandwidth_used, cost_native, failure_reason, created_at, updated_at
`

type CreateInternalTransferParams struct {
	Kind          InternalTransferKind
	AssetID       int16
	ProviderID    int16
	FromAddressID uuid.UUID
	ToAddressID   uuid.UUID
	Amount        pgtype.Numeric
}

// Treasury: movements between platform-controlled addresses (sweeps,
// fee top-ups, hot/cold rebalancing). Owned by internal/treasury.
func (q *Queries) CreateInternalTransfer(ctx context.Context, arg CreateInternalTransferParams) (InternalTransfer, error) {
	row := q.db.QueryRow(ctx, createInternalTransfer,
		arg.Kind,
		arg.AssetID,
		arg.ProviderID,
		arg.FromAddressID,
		arg.ToAddressID,
		arg.Amount,
	)
	var i InternalTransfer
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.AssetID,
		&i.ProviderID,
		&i.FromAddressID,
		&i.ToAddressID,
		&i.Amount,
		&i.Status,
		&i.TransactionID,
		&i.ExternalRef,
		&i.EnergyUsed,
		&i.BandwidthUsed,
		&i.CostNative,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failInternalTransfer = `-- name: FailInternalTransfer :one
UPDATE internal_transfers
SET status = 'failed', failure_reason = $2
WHERE id = $1 AND status IN ('queued', 'broadcast')
RETURNING id, kind, asset_id, provider_id, from_address_id, to_address_id, amount, status, transaction_id, external_ref, energy_used, bandwidth_used, cost_native, failure_reason, created_at, updated_at
`

type FailInternalTransferParams struct {
	ID            uuid.UUID
	FailureReason *string
}

func (q *Queries) FailInternalTransfer(ctx context.Context, arg FailInternalTransferParams) (InternalTransfer, error) {
	row := q.db.QueryRow(ctx, failInternalTransfer, arg.ID, arg.FailureReason)
	var i InternalTransfer
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.AssetID,
		&i.ProviderID,
		&i.FromAddressID,
		&i.ToAddressID,
		&i.Amount,
		&i.Status,
		&i.TransactionID,
		&i.ExternalRef,
		&i.EnergyUsed,
		&i.BandwidthUsed,
		&i.CostNative,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInternalTransfer = `-- name: GetInternalTransfer :one
SELECT id, kind, asset_id, provider_id, from_address_id, to_address_id, amount, status, transaction_id, external_ref, energy_used, bandwidth_used, cost_native, failure_reason, created_at, updated_at FROM internal_transfers WHERE id = $1
`

func (q *Queries) GetInternalTransfer(ctx context.Context, id uuid.UUID) (InternalTransfer, error) {
	row := q.db.QueryRow(ctx, getInternalTransfer, id)
	var i InternalTransfer
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.AssetID,
		&i.ProviderID,
		&i.FromAddressID,
		&i.ToAddressID,
		&i.Amount,
		&i.Status,
		&i.TransactionID,
		&i.ExternalRef,
		&i.EnergyUsed,
		&i.BandwidthUsed,
		&i.CostNative,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBroadcastInternalTransfers = `-- name: ListBroadcastInternalTransfers :many
SELECT t.id, t.kind, t.asset_id, t.provider_id, t.from_address_id, t.to_address_id, t.amount, t.status, t.transaction_id, t.external_ref, t.energy_used, t.bandwidth_used, t.cost_native, t.failure_reason, t.created_at, t.updated_at, tx.status AS tx_status, tx.confirmations, tx.fee_native, n.required_confirmations
FROM internal_transfers t
JOIN transactions tx ON tx.id = t.transaction_id
JOIN assets a        ON a.id = t.asset_id
JOIN networks n      ON n.id = a.network_id
WHERE t.status = 'broadcast'
ORDER BY t.created_at
LIMIT $1
`

type ListBroadcastInternalTransfersRow struct {
	InternalTransfer      InternalTransfer
	TxStatus              TxStatus
	Confirmations         int32
	FeeNative             pgtype.Numeric
	RequiredConfirmations int32
}

func (q *Queries) ListBroadcastInternalTransfers(ctx context.Context, limit int32) ([]ListBroadcastInternalTransfersRow, error) {
	rows, err := q.db.Query(ctx, listBroadcastInternalTransfers, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBroadcastInternalTransfersRow{}
	for rows.Next() {
		var i ListBroadcastInternalTransfersRow
		if err := rows.Scan(
			&i.InternalTransfer.ID,
			&i.InternalTransfer.Kind,
			&i.InternalTransfer.AssetID,
			&i.InternalTransfer.ProviderID,
			&i.InternalTransfer.FromAddressID,
			&i.InternalTransfer.ToAddressID,
			&i.InternalTransfer.Amount,
			&i.InternalTransfer.Status,
			&i.InternalTransfer.TransactionID,
			&i.InternalTransfer.ExternalRef,
			&i.InternalTransfer.EnergyUsed,
			&i.InternalTransfer.BandwidthUsed,
			&i.InternalTransfer.CostNative,
			&i.InternalTransfer.FailureReason,
			&i.InternalTransfer.CreatedAt,
			&i.InternalTransfer.UpdatedAt,
			&i.TxStatus,
			&i.Confirmations,
			&i.FeeNative,
			&i.RequiredConfirmations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInternalTransfers = `-- name: ListInternalTransfers :many
SELECT t.id, t.kind, t.asset_id, t.provider_id, t.from_address_id, t.to_address_id, t.amount, t.status, t.transaction_id, t.external_ref, t.energy_used, t.bandwidth_used, t.cost_native, t.failure_reason, t.created_at, t.updated_at, a.code AS asset_code, fa.address AS from_address, ta.address AS to_address
FROM internal_transfers t
JOIN assets a     ON a.id = t.asset_id
JOIN addresses fa ON fa.id = t.from_address_id
JOIN addresses ta ON ta.id = t.to_address_id
ORDER BY t.created_at DESC
LIMIT $1 OFFSET $2
`

type ListInternalTransfersParams struct {
	Limit  int32
	Offset int32
}

type ListInternalTransfersRow struct {
	InternalTransfer InternalTransfer
	AssetCode        string
	FromAddress      string
	ToAddress        string
}

func (q *Queries) ListInternalTransfers(ctx context.Context, arg ListInternalTransfersParams) ([]ListInternalTransfersRow, error) {
	rows, err := q.db.Query(ctx, listInternalTransfers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInternalTransfersRow{}
	for rows.Next() {
		var i ListInternalTransfersRow
		if err := rows.Scan(
			&i.InternalTransfer.ID,
			&i.InternalTransfer.Kind,
			&i.InternalTransfer.AssetID,
			&i.InternalTransfer.ProviderID,
			&i.InternalTransfer.FromAddressID,
			&i.InternalTransfer.ToAddressID,
			&i.InternalTransfer.Amount,
			&i.InternalTransfer.Status,
			&i.InternalTransfer.TransactionID,
			&i.InternalTransfer.ExternalRef,
			&i.InternalTransfer.EnergyUsed,
			&i.InternalTransfer.BandwidthUsed,
			&i.InternalTransfer.CostNative,
			&i.InternalTransfer.FailureReason,
			&i.InternalTransfer.CreatedAt,
			&i.InternalTransfer.UpdatedAt,
			&i.AssetCode,
			&i.FromAddress,
			&i.ToAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueuedInternalTransfers = `-- name: ListQueuedInternalTransfers :many
SELECT id, kind, asset_id, provider_id, from_address_id, to_address_id, amount, status, transaction_id, external_ref, energy_used, bandwidth_used, cost_native, failure_reason, created_at, updated_at FROM internal_transfers
WHERE status = 'queued'
ORDER BY created_at
LIMIT $1
`

func (q *Queries) ListQueuedInternalTransfers(ctx context.Context, limit int32) ([]InternalTransfer, error) {
	rows, err := q.db.Query(ctx, listQueuedInternalTransfers, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InternalTransfer{}
	for rows.Next() {
		var i InternalTransfer
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.AssetID,
			&i.ProviderID,
			&i.FromAddressID,
			&i.ToAddressID,
			&i.Amount,
			&i.Status,
			&i.TransactionID,
			&i.ExternalRef,
			&i.EnergyUsed,
			&i.BandwidthUsed,
			&i.CostNative,
			&i.FailureReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSweepCandidates = `-- name: ListSweepCandidates :many
SELECT b.address_id, b.asset_id, b.balance, b.as_of_block, b.updated_at, ad.id, ad.network_id, ad.provider_id, ad.wallet_id, ad.organization_id, ad.address, ad.memo, ad.kind, ad.derivation_index, ad.external_address_id, ad.is_active, ad.last_used_at, ad.created_at
FROM address_balances b
JOIN addresses ad ON ad.id = b.address_id
WHERE b.asset_id = $1
  AND ad.kind = 'deposit'
  AND ad.is_active
  AND b.balance >= $2
  AND NOT EXISTS (
      SELECT 1 FROM internal_transfers it
      WHERE it.from_address_id = b.address_id AND it.asset_id = b.asset_id AND it.status IN ('queued', 'broadcast')
  )
ORDER BY b.balance DESC
LIMIT $3
`

type ListSweepCandidatesParams struct {
	AssetID int16
	Balance pgtype.Numeric
	Limit   int32
}

type ListSweepCandidatesRow struct {
	AddressBalance AddressBalance
	Address        Address
}

// Deposit addresses holding at least the threshold of an asset and with no
// sweep already in flight.
func (q *Queries) ListSweepCandidates(ctx context.Context, arg ListSweepCandidatesParams) ([]ListSweepCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listSweepCandidates, arg.AssetID, arg.Balance, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSweepCandidatesRow{}
	for rows.Next() {
		var i ListSweepCandidatesRow
		if err := rows.Scan(
			&i.AddressBalance.AddressID,
			&i.AddressBalance.AssetID,
			&i.AddressBalance.Balance,
			&i.AddressBalance.AsOfBlock,
			&i.AddressBalance.UpdatedAt,
			&i.Address.ID,
			&i.Address.NetworkID,
			&i.Address.ProviderID,
			&i.Address.WalletID,
			&i.Address.OrganizationID,
			&i.Address.Address,
			&i.Address.Memo,
			&i.Address.Kind,
			&i.Address.DerivationIndex,
			&i.Address.ExternalAddressID,
			&i.Address.IsActive,
			&i.Address.LastUsedAt,
			&i.Address.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInternalTransferBroadcast = `-- name: MarkInternalTransferBroadcast :one
UPDATE internal_transfers
SET status = 'broadcast', transaction_id = $2, external_ref = $3
WHERE id = $1 AND status = 'queued'
RETURNING id, kind, asset_id, provider_id, from_address_id, to_address_id, amount, status, transaction_id, external_ref, energy_used, bandwidth_used, cost_native, failure_reason, created_at, updated_at
`

type MarkInternalTransferBroadcastParams struct {
	ID            uuid.UUID
	TransactionID uuid.NullUUID
	ExternalRef   *string
}

func (q *Queries) MarkInternalTransferBroadcast(ctx context.Context, arg MarkInternalTransferBroadcastParams) (InternalTransfer, error) {
	row := q.db.QueryRow(ctx, markInternalTransferBroadcast, arg.ID, arg.TransactionID, arg.ExternalRef)
	var i InternalTransfer
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.AssetID,
		&i.ProviderID,
		&i.FromAddressID,
		&i.ToAddressID,
		&i.Amount,
		&i.Status,
		&i.TransactionID,
		&i.ExternalRef,
		&i.EnergyUsed,
		&i.BandwidthUsed,
		&i.CostNative,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
